@startuml
'https://plantuml.com/sequence-diagram


class Question {
- intitule : string
- reponses : array
- bonnereponse : string
}


class Theme {
- libelle : string
}

Theme "1..1"--"0..*" Question


@enduml